config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Soft delete restore route concern
  concern :restorable do
    member do
      patch :restore
    end
  end

  devise_for :users,
             controllers: {
               sessions: 'users/sessions',
               registrations: 'users/registrations',
               passwords: 'users/passwords',
               confirmations: 'users/confirmations',
               unlocks: 'users/unlocks'
             }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'dashboard#index'

  # Dashboard
  get 'dashboard', to: 'dashboard#index'
  # BI Dashboard
  get 'bi_dashboard', to: 'bi_dashboard#index', as: :bi_dashboard

  # Work Order Namespace
  namespace :work_orders do
    resources :details, concerns: :restorable do
      member do
        patch :mark_complete
        get :confirm_delete
      end
    end
    resources :approvals, only: %i[index show update] do
      member do
        patch :approve
        patch :request_amendment
      end
    end
    resources :pay_calculations do
      member do
        get :worker_detail
      end
    end
    resources :mandays, concerns: :restorable
  end

  # Payslips
  resources :payslips, only: %i[index show] do
    collection do
      get :export
    end
  end

  # Inventory
  resources :inventories, concerns: :restorable do
    member do
      get :confirm_delete
    end
    resources :inventory_orders, concerns: :restorable do
      member do
        get :confirm_delete
      end
    end
  end

  # Workers
  resources :workers, concerns: :restorable do
    member do
      get :confirm_delete
    end
  end

  # Production
  resources :productions do
    member do
      get :confirm_delete
    end
  end

  # Master Data Namespace
  namespace :master_data do
    resources :vehicles, concerns: :restorable do
      member do
        get :confirm_delete
      end
    end

    resources :work_order_rates, concerns: :restorable do
      member do
        get :confirm_delete
      end
    end

    resources :blocks, concerns: :restorable do
      member do
        get :confirm_delete
      end
    end

    resources :units, concerns: :restorable do
      member do
        get :confirm_delete
      end
    end

    resources :categories, concerns: :restorable do
      member do
        get :confirm_delete
      end
    end

    resources :mills do
      member do
        get :confirm_delete
      end
    end
  end

  # User Management Namespace
  namespace :user_management do
    resources :roles, concerns: :restorable do
      member do
        get :confirm_delete
      end
    end

    resources :users, concerns: :restorable do
      member do
        get :confirm_delete
      end
    end
  end
end

app/controllers/master_data/blocks_controller.rb
# frozen_string_literal: true

module MasterData
  class BlocksController < ApplicationController
    include RansackMultiSort
    include SoftDeletableController

    before_action :set_block, only: %i[show edit update destroy confirm_delete]

    def index
      authorize Block, policy_class: MasterData::BlockPolicy

      apply_ransack_search(policy_scope(Block, policy_scope_class: MasterData::BlockPolicy::Scope).order(id: :desc))
      @pagy, @blocks = paginate_results(@q.result)
    end

    def show
      authorize @block, policy_class: MasterData::BlockPolicy

      if turbo_frame_request?
        render layout: false
      else
        redirect_to master_data_blocks_path
      end
    end

    def new
      @block = Block.new
      authorize @block, policy_class: MasterData::BlockPolicy

      if turbo_frame_request?
        render layout: false
      else
        redirect_to master_data_blocks_path
      end
    end

    def create
      @block = Block.new(block_params)
      authorize @block, policy_class: MasterData::BlockPolicy

      respond_to do |format|
        if @block.save
          format.turbo_stream do
            flash.now[:notice] = 'Block was successfully created.'
          end
          format.html { redirect_to master_data_blocks_path, notice: 'Block was successfully created.' }
        else
          format.turbo_stream do
            render turbo_stream: turbo_stream.replace('modal', partial: 'master_data/blocks/form', locals: { block: @block }),
                   status: :unprocessable_entity
          end
          format.html { render :new, status: :unprocessable_entity }
        end
      end
    end

    def edit
      authorize @block, policy_class: MasterData::BlockPolicy

      if turbo_frame_request?
        render layout: false
      else
        redirect_to master_data_blocks_path
      end
    end

    def update
      authorize @block, policy_class: MasterData::BlockPolicy

      respond_to do |format|
        if @block.update(block_params)
          format.turbo_stream do
            flash.now[:notice] = 'Block was successfully updated.'
          end
          format.html { redirect_to master_data_blocks_path, notice: 'Block was successfully updated.' }
        else
          format.turbo_stream do
            render turbo_stream: turbo_stream.replace('modal', partial: 'master_data/blocks/form', locals: { block: @block }),
                   status: :unprocessable_entity
          end
          format.html { render :edit, status: :unprocessable_entity }
        end
      end
    end

    def confirm_delete
      authorize @block, policy_class: MasterData::BlockPolicy

      # Only render the modal if Turbo frame request
      if turbo_frame_request?
        render layout: false
      else
        redirect_to master_data_blocks_path
      end
    end

    def destroy
      authorize @block, policy_class: MasterData::BlockPolicy
      super
    end

    def restore
      @block = Block.with_discarded.find(params[:id])
      authorize @block, policy_class: MasterData::BlockPolicy
      super
    end

    private

    def set_block
      @block = Block.find_by(id: params[:id])
      return if @block.present?

      if turbo_frame_request?
        render turbo_stream: turbo_stream.replace('modal', ''), status: :ok
      else
        redirect_to master_data_blocks_path
      end
    end

    def block_params
      params.require(:block).permit(
        :block_number,
        :hectarage
      )
    end
  end
end

app/controllers/master_data/categories_controller.rb
# frozen_string_literal: true

module MasterData
  class CategoriesController < ApplicationController
    include RansackMultiSort
    include SoftDeletableController

    before_action :set_category, only: %i[show edit update destroy confirm_delete]

    def index
      authorize Category, policy_class: MasterData::CategoryPolicy

      apply_ransack_search(policy_scope(Category,
                                        policy_scope_class: MasterData::CategoryPolicy::Scope).order(id: :desc))
      @pagy, @categories = paginate_results(@q.result.includes(:parent))
    end

    def show
      authorize @category, policy_class: MasterData::CategoryPolicy
    end

    def new
      @category = Category.new
      authorize @category, policy_class: MasterData::CategoryPolicy

      if turbo_frame_request?
        render layout: false
      else
        redirect_to master_data_categories_path
      end
    end

    def create
      @category = Category.new(category_params)
      authorize @category, policy_class: MasterData::CategoryPolicy

      respond_to do |format|
        if @category.save
          format.turbo_stream do
            flash.now[:notice] = 'Category was successfully created.'
          end
          format.html { redirect_to master_data_categories_path, notice: 'Category was successfully created.' }
        else
          format.turbo_stream do
            render turbo_stream: turbo_stream.replace('modal', partial: 'master_data/categories/form', locals: { category: @category }),
                   status: :unprocessable_entity
          end
          format.html { render :new, status: :unprocessable_entity }
        end
      end
    end

    def edit
      authorize @category, policy_class: MasterData::CategoryPolicy

      if turbo_frame_request?
        render layout: false
      else
        redirect_to master_data_categories_path
      end
    end

    def update
      authorize @category, policy_class: MasterData::CategoryPolicy

      respond_to do |format|
        if @category.update(category_params)
          format.turbo_stream do
            flash.now[:notice] = 'Category was successfully updated.'
          end
          format.html { redirect_to master_data_categories_path, notice: 'Category was successfully updated.' }
        else
          format.turbo_stream do
            render turbo_stream: turbo_stream.replace('modal', partial: 'master_data/categories/form', locals: { category: @category }),
                   status: :unprocessable_entity
          end
          format.html { render :edit, status: :unprocessable_entity }
        end
      end
    end

    def confirm_delete
      @category = Category.find_by(id: params[:id])
      redirect_to master_data_categories_path, alert: 'Category not found' and return unless @category

      authorize @category, policy_class: MasterData::CategoryPolicy

      # Only show the modal
      if turbo_frame_request?
        render layout: false
      else
        redirect_to master_data_categories_path
      end
    end

    def destroy
      authorize @category, policy_class: MasterData::CategoryPolicy
      super
    end

    def restore
      @category = Category.with_discarded.find(params[:id])
      authorize @category, policy_class: MasterData::CategoryPolicy
      super
    end

    private

    def set_category
      @category = Category.find_by(id: params[:id])
      return if @category.present?

      if turbo_frame_request?
        render turbo_stream: turbo_stream.replace('modal', ''), status: :ok
      else
        redirect_to master_data_categories_path
      end
    end

    def category_params
      params.require(:category).permit(
        :name,
        :category_type,
        :parent_id
      )
    end
  end
end

app/controllers/master_data/mills_controller.rb
# frozen_string_literal: true

module MasterData
  class MillsController < ApplicationController
    include RansackMultiSort

    before_action :set_mill, only: %i[show edit update destroy confirm_delete]

    def index
      authorize Mill, policy_class: MasterData::MillPolicy

      apply_ransack_search(policy_scope(Mill, policy_scope_class: MasterData::MillPolicy::Scope).order(id: :desc))
      @pagy, @mills = paginate_results(@q.result)
    end

    def show
      authorize @mill, policy_class: MasterData::MillPolicy

      if turbo_frame_request?
        render layout: false
      else
        redirect_to master_data_mills_path
      end
    end

    def new
      @mill = Mill.new
      authorize @mill, policy_class: MasterData::MillPolicy

      if turbo_frame_request?
        render layout: false
      else
        redirect_to master_data_mills_path
      end
    end

    def create
      @mill = Mill.new(mill_params)
      authorize @mill, policy_class: MasterData::MillPolicy

      respond_to do |format|
        if @mill.save
          format.turbo_stream do
            flash.now[:notice] = 'Mill was successfully created.'
          end
          format.html { redirect_to master_data_mills_path, notice: 'Mill was successfully created.' }
        else
          format.turbo_stream do
            render turbo_stream: turbo_stream.replace('modal', partial: 'master_data/mills/form', locals: { mill: @mill }),
                   status: :unprocessable_entity
          end
          format.html { render :new, status: :unprocessable_entity }
        end
      end
    end

    def edit
      authorize @mill, policy_class: MasterData::MillPolicy

      if turbo_frame_request?
        render layout: false
      else
        redirect_to master_data_mills_path
      end
    end

    def update
      authorize @mill, policy_class: MasterData::MillPolicy

      respond_to do |format|
        if @mill.update(mill_params)
          format.turbo_stream do
            flash.now[:notice] = 'Mill was successfully updated.'
          end
          format.html { redirect_to master_data_mills_path, notice: 'Mill was successfully updated.' }
        else
          format.turbo_stream do
            render turbo_stream: turbo_stream.replace('modal', partial: 'master_data/mills/form', locals: { mill: @mill }),
                   status: :unprocessable_entity
          end
          format.html { render :edit, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      authorize @mill, policy_class: MasterData::MillPolicy

      respond_to do |format|
        if @mill.destroy
          format.turbo_stream do
            flash.now[:notice] = 'Mill was successfully deleted.'
          end
          format.html { redirect_to master_data_mills_path, notice: 'Mill was successfully deleted.' }
        else
          format.turbo_stream do
            flash.now[:alert] = @mill.errors.full_messages.join(', ')
            render turbo_stream: [
              turbo_stream.update('flash', partial: 'layouts/flash')
            ]
          end
          format.html { redirect_to master_data_mills_path, alert: @mill.errors.full_messages.join(', ') }
        end
      end
    end

    # GET /master_data/mills/:id/confirm_delete
    def confirm_delete
      authorize @mill, policy_class: MasterData::MillPolicy

      # Only render the modal if Turbo frame request
      if turbo_frame_request?
        render layout: false
      else
        redirect_to master_data_mills_path
      end
    end

    private

    def set_mill
      @mill = Mill.find(params[:id])
    end

    def mill_params
      params.require(:mill).permit(:name)
    end
  end
end

app/controllers/master_data/units_controller.rb
# frozen_string_literal: true

module MasterData
  class UnitsController < ApplicationController
    include RansackMultiSort
    include SoftDeletableController

    before_action :set_unit, only: %i[show edit update destroy confirm_delete]

    def index
      authorize Unit, policy_class: MasterData::UnitPolicy

      apply_ransack_search(policy_scope(Unit, policy_scope_class: MasterData::UnitPolicy::Scope).order(id: :desc))
      @pagy, @units = paginate_results(@q.result)
    end

    def show
      authorize @unit, policy_class: MasterData::UnitPolicy
    end

    def new
      @unit = Unit.new
      authorize @unit, policy_class: MasterData::UnitPolicy

      if turbo_frame_request?
        render layout: false
      else
        redirect_to master_data_units_path
      end
    end

    def create
      @unit = Unit.new(unit_params)
      authorize @unit, policy_class: MasterData::UnitPolicy

      respond_to do |format|
        if @unit.save
          format.turbo_stream do
            flash.now[:notice] = 'Unit was successfully created.'
          end
          format.html { redirect_to master_data_units_path, notice: 'Unit was successfully created.' }
        else
          format.turbo_stream do
            render turbo_stream: turbo_stream.replace('modal', partial: 'master_data/units/form', locals: { unit: @unit }),
                   status: :unprocessable_entity
          end
          format.html { render :new, status: :unprocessable_entity }
        end
      end
    end

    def edit
      authorize @unit, policy_class: MasterData::UnitPolicy

      if turbo_frame_request?
        render layout: false
      else
        redirect_to master_data_units_path
      end
    end

    def update
      authorize @unit, policy_class: MasterData::UnitPolicy

      respond_to do |format|
        if @unit.update(unit_params)
          format.turbo_stream do
            flash.now[:notice] = 'Unit was successfully updated.'
          end
          format.html { redirect_to master_data_units_path, notice: 'Unit was successfully updated.' }
        else
          format.turbo_stream do
            render turbo_stream: turbo_stream.replace('modal', partial: 'master_data/units/form', locals: { unit: @unit }),
                   status: :unprocessable_entity
          end
          format.html { render :edit, status: :unprocessable_entity }
        end
      end
    end

    def confirm_delete
      authorize @unit, policy_class: MasterData::UnitPolicy

      # Only show the modal
      if turbo_frame_request?
        render layout: false
      else
        redirect_to master_data_unit_path
      end
    end

    def destroy
      authorize @unit, policy_class: MasterData::UnitPolicy
      super
    end

    def restore
      @unit = Unit.with_discarded.find(params[:id])
      authorize @unit, policy_class: MasterData::UnitPolicy
      super
    end

    private

    def set_unit
      @unit = Unit.find_by(id: params[:id])
      return if @unit.present?

      if turbo_frame_request?
        render turbo_stream: turbo_stream.replace('modal', ''), status: :ok
      else
        redirect_to master_data_units_path
      end
    end

    def unit_params
      params.require(:unit).permit(
        :name,
        :unit_type
      )
    end
  end
end

app/views/master_data/mills/_form.html.erb
<div class="modal-content">
  <%= form_with(model: [:master_data, mill], class: "needs-validation", novalidate: true, data: { action: "turbo:submit-end->modal#formSubmitted" }) do |form| %>
    <div class="modal-header">
      <h5 class="modal-title"><strong><%= mill.persisted? ? 'Edit Mill' : 'Add New Mill' %></strong></h5>
      <button type="button" class="btn-close custom-close-btn" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
    <div class="modal-body">
      <% if mill.errors.any? %>
        <div class="alert alert-danger">
          <h5><%= pluralize(mill.errors.count, "error") %> prohibited this mill from being saved:</h5>
          <ul>
            <% mill.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="mb-3">
        <%= form.label :name, "Mill Name", class: "form-label fw-bold" %>
        <%= form.text_field :name, placeholder: "Enter Mill Name", class: "form-control", required: true %>
      </div>
    </div>
    <div class="modal-footer">
      <%= button_tag type: :submit, class: "btn btn-success" do %>
        <i class="bi bi-save-fill text-white me-1"></i> Save
      <% end %>
    </div>
  <% end %>
</div>

app/views/master_data/mills/_mill_row.html.erb
<tr id="<%= dom_id(mill) %>">
  <td class="text-center">
    <div class="action-buttons">
      <% if record_policy(mill, MasterData::MillPolicy).show? %>
        <%= link_to master_data_mill_path(mill), class: "action-btn info", title: "View Details", **modal_link_data do %>
          <i class="bi bi-info-circle-fill"></i>
        <% end %>
      <% end %>
      <% if record_policy(mill, MasterData::MillPolicy).edit? %>
        <%= link_to edit_master_data_mill_path(mill), class: "action-btn warning", title: "Edit", **modal_link_data do %>
          <i class="bi bi-pencil-fill"></i>
        <% end %>
      <% end %>
      <% if record_policy(mill, MasterData::MillPolicy).confirm_delete? %>
        <%= link_to confirm_delete_master_data_mill_path(mill),
                    class: "action-btn danger",
                    title: "Delete",
                    **modal_link_data(size: "modal-md") do %>
          <i class="bi bi-trash-fill"></i>
        <% end %>
      <% end %>
    </div>
  </td>
  <td class="text-center"><%= mill.name %></td>
  <td class="text-center"><%= mill.created_at.strftime('%d %b %Y') %></td>
</tr>

app/views/master_data/mills/_modal.html.erb
<%# Mills Modal - Uses Shared Modal Component %>
<%= render "shared/modal", **modal_config(
      id: "millModal",
      default_size: "modal-lg",
      centered: true,
      frame_id: "modal"
    ) %>

app/views/master_data/mills/confirm_delete.html.erb
<%= turbo_frame_tag "modal" do %>
  <%= render "shared/confirm_delete",
             item_name: @mill.name,
             item_type: "Mill",
             delete_path: master_data_mill_path(@mill),
             form_id: "deleteMillForm" %>
<% end %>

app/views/master_data/mills/create.turbo_stream.erb
<%= turbo_stream.prepend "mill_rows", partial: "master_data/mills/mill_row", locals: { mill: @mill } %>
<%= turbo_stream.update "modal", "" %>
<%= turbo_stream.update "flash_messages", partial: "shared/flash" %>

app/views/master_data/mills/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@mill) %>
<%= turbo_stream.update "modal", "" %>
<%= turbo_stream.update "flash_messages", partial: "shared/flash" %>
<%= turbo_stream.update "url-manager",
    partial: "shared/url_updater",
    locals: { url: master_data_mills_path } %>

app/views/master_data/mills/edit.html.erb
<%= turbo_frame_tag "modal" do %>
  <%= render 'form', mill: @mill %>
<% end %>

app/views/master_data/mills/index.html.erb
<div id="url-manager"></div>
<div id="mills" class="container-fluid px-4 py-4" data-controller="multi-sort">
  <div class="card shadow-sm">
    <div class="mills_page">
      <h1 class="mb-0">Master Data - Mills</h1>
      <div class="d-flex justify-content-end">
        <% if record_policy(Mill.new, MasterData::MillPolicy).new? %>
          <%= link_to new_master_data_mill_path,
                      class: "add-button btn btn-primary btn-sm",
                      **modal_link_data do %>
            <i class="bi bi-plus-circle-fill text-white me-1"></i> Add Mill
          <% end %>
        <% end %>
      </div>
      <div class="card-body">
        <%= search_form_for @q, url: master_data_mills_path, html: { id: 'mill-search-form', data: { controller: "search-form", action: "submit->search-form#resetPage" } } do |f| %>
          <div class="table-responsive">
            <table class="table table-hover table-sm mb-0">
              <thead class="header-row">
                <tr class="header-row">
                  <th></th>
                  <th class="text-center"><%= sort_link(@q, :name, 'Mill Name') %></th>
                  <th class="text-center"><%= sort_link(@q, :created_at, 'Created At') %></th>
                </tr>
                <tr>
                  <th class="text-center">
                    <div class="filter-buttons">
                      <%= link_to 'Reset', master_data_mills_path, class: "btn reset-btn", style: 'width: 120px;' %>
                    </div>
                  </th>
                  <th><%= f.search_field :name_cont, class: 'form-control form-control-sm', placeholder: 'Search Name...', data: { action: "input->search-form#autoSubmit" } %></th>
                  <th></th>
                </tr>
              </thead>
              <tbody id="mill_rows">
                <% if @mills.any? %>
                  <%= render partial: 'mill_row', collection: @mills, as: :mill %>
                <% else %>
                  <tr>
                    <td colspan="3" class="text-center text-muted py-4">
                      No mills found.
                      <% if record_policy(Mill.new, MasterData::MillPolicy).new? %>
                        <%= link_to 'Add a new mill', new_master_data_mill_path, class: 'text-decoration-none', **modal_link_data %>
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        <% end %>
        <div class="d-flex justify-content-between align-items-center mt-3">
          <div class="d-flex align-items-center gap-2">
            <span class="text-muted small">Show</span>
            <%= per_page_selector(current: params[:per_page] || 10) %>
            <span class="text-muted small"><%== @pagy.info_tag(item_name: 'Mills') %></span>
          </div>
          <div><%== pagy_bootstrap_nav(@pagy) if @pagy.pages > 1 %></div>
        </div>
      </div>
    </div>
  </div>
</div>
<%= render "modal" %>

app/views/master_data/mills/new.html.erb
<%= turbo_frame_tag "modal" do %>
  <%= render 'form', mill: @mill %>
<% end %>

app/views/master_data/mills/show.html.erb
<%= turbo_frame_tag "modal" do %>
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title"><strong>Mill Details</strong></h5>
      <button type="button" class="btn-close custom-close-btn" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
    <div class="modal-body">
      <dl class="row">
        <dt class="col-sm-3">Name:</dt>
        <dd class="col-sm-9"><%= @mill.name %></dd>
        <dt class="col-sm-3">Created:</dt>
        <dd class="col-sm-9"><%= @mill.created_at.strftime('%d %b %Y %H:%M') %></dd>
        <dt class="col-sm-3">Updated:</dt>
        <dd class="col-sm-9"><%= @mill.updated_at.strftime('%d %b %Y %H:%M') %></dd>
      </dl>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
    </div>
  </div>
<% end %>

app/views/master_data/mills/update.turbo_stream.erb
<%= turbo_stream.replace dom_id(@mill), partial: "master_data/mills/mill_row", locals: { mill: @mill } %>
<%= turbo_stream.update "modal", "" %>
<%= turbo_stream.update "flash_messages", partial: "shared/flash" %>